server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    url: mongodb://localhost:27017/
    max_pool_size: 20
  redis:
    addr: 127.0.0.1:6379
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  etcd:
    addr: 39.96.116.239:2379
    username: root
    password: root